<a href="https://colab.research.google.com/github/Tetsu-M19/Numpy/blob/master/Numpy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
>>> import numpy as np

In [2]:
>>> np.array([1,2,3])

array([1, 2, 3])

In [3]:
>>> np.arange(5)

array([0, 1, 2, 3, 4])

In [5]:
>>> np.array([[1,2,3],
               [4,5,6,]])

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
>>> np.zeros([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
>>> np.ones([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
>>> np.array([1,2,3]) + 2

array([3, 4, 5])

In [9]:
>>> a = np.array([1,2,3,4])
>>> a.sum() 

10

**要素数が同じ時計算可**

In [10]:
>>> b = np.array([1,2])
>>> c = np.array([2,3])
>>> np.dot(b,c)

8

In [11]:
>>> np.sqrt(9)

3.0

In [12]:
>>> np.random.rand()

0.17022262817000422

In [13]:
>>> r =  np.random.rand(3)
>>> r

array([0.43563617, 0.06932205, 0.36367202])

In [14]:
>>> type(r)

numpy.ndarray

In [15]:
>>> np.random.rand(2,2)

array([[0.89660306, 0.17541211],
       [0.10049372, 0.28867317]])

In [16]:
>>> np.random.randint(100)

20

In [17]:
>>> x = np.array([[11,12,13],
                 [21,22,23],
                 [31,32,33]])
>>> print(x)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [19]:
>>> np.array([[1,2,3],
              [4,5,6]]) * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [22]:
>>> a = np.array([[1, 1, 2],
                 [3, 5, 8]])
>>> a.sum()

20

In [28]:
>>> a = np.array([[1, 2, 3],
                  [4, 5, 6]])
>>> b = np.array([[2, 4],
                  [3, 6],
                  [4, 8]])
>>> np.dot(a, b)

array([[20, 40],
       [47, 94]])

In [39]:
>>> a = np.array([2, 1])
>>> b = np.array([1, 3])
>>> c = np.dot(a,b)
>>> a = a**2
>>> a = a.sum()
>>> a = np.sqrt(a)
>>> b = b**2
>>> b = b.sum()
>>> b = np.sqrt(b)
>>> d = a*b
>>> e = c/d
>>> e = round(e,2)
>>> print(e)

0.71
